/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import gsap from 'gsap';

export function BuildSkateBoard({
  pose,
  wheelTextureURL,
  deckTextureURL,
  truckTextureURL,
  truckColor,
  boltColor,
  wheelTextureURLs,
  deckTextureURLs,
}) {
  const { nodes, materials } = useGLTF('/skateboard.gltf')
  let constantWheelSpin = false;
  const wheelRef = useRef([])

  // ─── Manual Texture Loading (Non-suspense) ──────────────────────────────────
  const [wheelTexture, setWheelTexture] = useState(null);
  const [deckTexture, setDeckTexture] = useState(null);
  const [truckTexture, setTruckTexture] = useState(null);

  // Initial/Default Textures (Keep these suspended as they load once)
  const defaultWheel = useTexture('/skateboard/SkateWheel1.png');
  const defaultDeck = useTexture('/skateboard/Deck.webp');
  const defaultTruck = useTexture('https://images.unsplash.com/photo-1575722290270-626b0208df99?q=80&w=435&auto=format&fit=crop');

  const silentManager = useMemo(() => new THREE.LoadingManager(), []);
  const silentTextureLoader = useMemo(() => new THREE.TextureLoader(silentManager), [silentManager]);

  useEffect(() => {
    if (!wheelTextureURL) return;
    silentTextureLoader.load(wheelTextureURL, (tex) => {
      tex.flipY = false;
      tex.colorSpace = THREE.SRGBColorSpace;
      setWheelTexture(tex);
    });
  }, [wheelTextureURL, silentTextureLoader]);

  useEffect(() => {
    if (!deckTextureURL) return;
    silentTextureLoader.load(deckTextureURL, (tex) => {
      tex.flipY = false;
      tex.colorSpace = THREE.SRGBColorSpace;
      setDeckTexture(tex);
    });
  }, [deckTextureURL, silentTextureLoader]);

  useEffect(() => {
    if (!truckTextureURL) return;
    silentTextureLoader.load(truckTextureURL, (tex) => {
      tex.flipY = false;
      tex.colorSpace = THREE.SRGBColorSpace;
      setTruckTexture(tex);
    });
  }, [truckTextureURL, silentTextureLoader]);

  const wheelMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: wheelTexture || defaultWheel,
      roughness: 0.3
    })
  }, [wheelTexture, defaultWheel])

  const deckMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: deckTexture || defaultDeck,
      roughness: 0.5
    })
  }, [deckTexture, defaultDeck])

  const truckMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      roughness: 0.5,
      metalness: 0.5
    })
  }, [truckTexture, defaultTruck])


  const GripTapeTexture = useTexture('/skateboard/grip.jpg')
  const gripTapeDiffuse = useTexture("/skateboard/griptape-diffuse.webp");
  const gripTapeRoughness = useTexture("/skateboard/griptape-roughness.webp");


  const GripTapeMaterial = useMemo(() => {
    const mertarial = new THREE.MeshStandardMaterial({
      map: GripTapeTexture,
      bumpMap: gripTapeDiffuse,
      roughnessMap: gripTapeRoughness,
      roughness: 0.5
    })
    if (gripTapeDiffuse) {
      gripTapeDiffuse.wrapS = THREE.RepeatWrapping;
      gripTapeDiffuse.wrapT = THREE.RepeatWrapping;
      gripTapeDiffuse.repeat.set(9, 9);
      gripTapeDiffuse.needsUpdate = true;

      gripTapeRoughness.wrapS = THREE.RepeatWrapping;
      gripTapeRoughness.wrapT = THREE.RepeatWrapping;
      gripTapeRoughness.repeat.set(9, 9);
      gripTapeRoughness.needsUpdate = true;

      gripTapeRoughness.anisotropy = 8;
    }
    return mertarial

  }, [])


  useEffect(() => {
    console.log("truck color is ", truckColor)
  }, [truckColor])


  const positions = useMemo(
    () =>
      ({
        upright: {
          rotation: [0, 0, 0],
          position: [0, 0, 0],
        },
        side: {
          rotation: [0, 0, 1.7],
          position: [0, 0.295, 0],
        },
      }),
    []
  );




  console.log(nodes)
  return (
    <group dispose={null}
      rotation={positions[pose].rotation}
      position={positions[pose].position}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GripTape.geometry}
        material={GripTapeMaterial}
        position={[0, 0.286, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel1.geometry}
        material={wheelMaterial}
        position={[0.238, 0.086, 0.635]}

      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel2.geometry}
        material={wheelMaterial}
        position={[-0.237, 0.086, 0.635]}

      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Deck.geometry}
        material={deckMaterial}
        position={[0, 0.271, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel4.geometry}
        material={wheelMaterial}
        position={[-0.238, 0.086, -0.635]}
        rotation={[Math.PI, 0, Math.PI]}

      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bolts.geometry}
        material-color={boltColor}
        position={[0, 0.198, 0]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel3.geometry}
        material={wheelMaterial}
        position={[0.237, 0.086, -0.635]}
        rotation={[Math.PI, 0, Math.PI]}

      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Baseplates.geometry}
        material={truckMaterial}
        material-color={truckColor}
        position={[0, 0.211, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Truck1.geometry}
        material={truckMaterial}
        material-color={truckColor}
        position={[0, 0.101, -0.617]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Truck2.geometry}
        material={truckMaterial}
        material-color={truckColor}
        position={[0, 0.101, 0.617]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('/skateboard.gltf')