// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from "three";
// import React, { useEffect, useMemo, useRef } from 'react'
// import { useGLTF, useTexture } from '@react-three/drei'
// import { useFrame } from "@react-three/fiber";
// import gsap from 'gsap';

// export function Skateboard(props) {
//   const { nodes, materials } = useGLTF('/skateboard.gltf')
//     let constantWheelSpin = false;
//   const wheelRef = useRef([]) 

//     const wheelTexture = useTexture('/skateboard/SkateWheel1.png')
//     wheelTexture.flipY = false;
//     wheelTexture.colorSpace = THREE.SRGBColorSpace;

//     const wheelMaterial = useMemo(() => {
//         return new THREE.MeshStandardMaterial({
//             map: wheelTexture,
//             roughness:0.3
//         })
//     }, [wheelTexture])

//     const deckTexture = useTexture('/skateboard/Deck.webp')
//     deckTexture.flipY = false;
//     deckTexture.colorSpace = THREE.SRGBColorSpace;

//     const deckMaterial = useMemo(()=> {
//         return new THREE.MeshStandardMaterial({
//             map:deckTexture,
//             roughness:0.5
//         })
//     },[])

//     const truckTexture = useTexture('https://images.unsplash.com/photo-1575722290270-626b0208df99?q=80&w=435&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')

//     const truckMaterial = useMemo(() => {
//         return new THREE.MeshStandardMaterial({
//             map:truckTexture,
//             roughness:0.5,
//             metalness:0.5
//         })
//     },[])


//     const GripTapeTexture = useTexture('/skateboard/grip.jpg')
//     const gripTapeDiffuse = useTexture("/skateboard/griptape-diffuse.webp");
//   const gripTapeRoughness = useTexture("/skateboard/griptape-roughness.webp");


//     const GripTapeMaterial = useMemo(()=> {
//         const mertarial = new THREE.MeshStandardMaterial({
//             map:GripTapeTexture,
//             bumpMap:gripTapeDiffuse,
//             roughnessMap:gripTapeRoughness,
//             roughness:0.5
//         })
//         if (gripTapeDiffuse) {
//       gripTapeDiffuse.wrapS = THREE.RepeatWrapping;
//       gripTapeDiffuse.wrapT = THREE.RepeatWrapping;
//       gripTapeDiffuse.repeat.set(9, 9);
//       gripTapeDiffuse.needsUpdate = true;

//       gripTapeRoughness.wrapS = THREE.RepeatWrapping;
//       gripTapeRoughness.wrapT = THREE.RepeatWrapping;
//       gripTapeRoughness.repeat.set(9, 9);
//       gripTapeRoughness.needsUpdate = true;

//       gripTapeRoughness.anisotropy = 8;
//     }
//     return mertarial
        
//     },[])

//     const addWheelRefs =(ref)=> {
//         if(ref && !wheelRef.current.includes(ref)){
//             wheelRef.current.push(ref);
//         }
//     }


//       useFrame(() => {
//     if (!wheelRef.current && constantWheelSpin) return;
//     for (const wheel of wheelRef.current) {
//       wheel.rotation.x += 0.2;
//     }
//   });

// //     useEffect(() => {
// //     if (!wheelRef.current) return;
// //     for (const wheel of wheelRef.current) {
// //       gsap.to(wheel.rotation, {
// //         x: "+=30",
// //         duration: 2.5,
// //         ease: "circ.out",
// //         onComplete: () => {
// //           constantWheelSpin = true;
// //         }
// //       });
// //     }
// //   }, []);


//   console.log(nodes)
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.GripTape.geometry}
//         material={GripTapeMaterial}
//         position={[0, 0.286, -0.002]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel1.geometry}
//         material={wheelMaterial}
//         position={[0.238, 0.086, 0.635]}
//         ref={addWheelRefs}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel2.geometry}
//         material={wheelMaterial}
//         position={[-0.237, 0.086, 0.635]}
//         ref={addWheelRefs}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Deck.geometry}
//         material={deckMaterial}
//         position={[0, 0.271, -0.002]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel4.geometry}
//         material={wheelMaterial}
//         position={[-0.238, 0.086, -0.635]}
//         rotation={[Math.PI, 0, Math.PI]}
//         ref={addWheelRefs}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bolts.geometry}
//         material={nodes.Bolts.material}
//         position={[0, 0.198, 0]}
//         rotation={[Math.PI, 0, Math.PI]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Wheel3.geometry}
//         material={wheelMaterial}
//         position={[0.237, 0.086, -0.635]}
//         rotation={[Math.PI, 0, Math.PI]}
//         ref={addWheelRefs}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Baseplates.geometry}
//         material={nodes.Baseplates.material}
//         position={[0, 0.211, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Truck1.geometry}
//         material={truckMaterial}
//         position={[0, 0.101, -0.617]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Truck2.geometry}
//         material={truckMaterial}
//         position={[0, 0.101, 0.617]}
//         rotation={[Math.PI, 0, Math.PI]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/skateboard.gltf')


